### PR TITLE
Bump to r27

### PR DESCRIPTION
**Pull request by licy183**

### CODE REVIEW

**Comment by Biswa96** [comment]
I have tried to build r27 in my fork with all darwin and windows prebuilts removed. Build Toolchain job failed with out of disk space after running 4h 39m 54s.

I could try to shallow clone every project in manifest file. That may remove git version information (not the clang/llvm actual version). Is that ok for this project?

Also, do you build lldb? If not, lldb dependencies can be removed too.

**Comment by licy183** [comment]
> I could try to shallow clone every project in manifest file. That may remove git version information (not the clang/llvm actual version). Is that ok for this project?

IMO this will not work. During the build process, patches are applied according to the output of `git rev-list --count HEAD`, and shallow clone will obviously break it.

> Also, do you build lldb? If not, lldb dependencies can be removed too.

I didn't compile lldb. I don't think that removing the source code of lldb's deps will help a lot anyway..

**Comment by Biswa96** [comment]
> During the build process, patches are applied according to the output of `git rev-list --count HEAD`, and shallow clone will obviously break it.

That does not mean shallow clone can not be done in repositories other than llvm-project, right?

**Comment by Biswa96** [comment]
> During the build process, patches are applied according to the output of `git rev-list --count HEAD`, and shallow clone will obviously break it.

But the patches were applied correctly according to the logs. I have compared the logs between shallow clone and full history clone. I found similar patches are applied.

**Comment by licy183** [comment]
> But the patches were applied correctly according to the logs. I have compared the logs between shallow clone and full history clone. I found similar patches are applied.

I'm not sure about it. Maybe we can give it a try.

**Pull request merged**
